case $CIRCLE_NODE_INDEX in
  0) BROWSER_NAME='firefox'  BROWSER_VERSION='33' TEST_SERVER_PORT=8884 npm test ;;
  1) BROWSER_NAME='chrome'  BROWSER_VERSION='36' TEST_SERVER_PORT=8885 npm test ;;
  2) BROWSER_NAME='chrome'  BROWSER_VERSION='37' TEST_SERVER_PORT=8886 npm test ;;
  3) BROWSER_NAME='chrome'  BROWSER_VERSION='38' TEST_SERVER_PORT=8887 npm test ;;
esac
